### ISSUE TITLE
Doesn't work with recent version 1.20.1 (Purpur)

### ISSUE THREAD

**Issue by Senpapuh** [kejonaMC/GeyserBlockJavaPlayers#10]
log:
`[Server thread/ERROR]: Error occurred while enabling GeyserBlockJavaPlayers v1.2-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)'
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:178) ~[GeyserBlockJavaPlayers-Spigot (2).jar:?]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:466) ~[GeyserBlockJavaPlayers-Spigot (2).jar:?]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:354) ~[GeyserBlockJavaPlayers-Spigot (2).jar:?]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[GeyserBlockJavaPlayers-Spigot (2).jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3494) ~[GeyserBlockJavaPlayers-Spigot (2).jar:?]
	at com.github.camotoy.geyserblockjavaplayers.common.Configurate.create(Configurate.java:40) ~[GeyserBlockJavaPlayers-Spigot (2).jar:?]
	at com.github.camotoy.geyserblockjavaplayers.GeyserBlockJavaPlayersSpigot.onEnable(GeyserBlockJavaPlayersSpigot.java:17) ~[GeyserBlockJavaPlayers-Spigot (2).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:650) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:561) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2006]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:54:51] [Server thread/INFO]: [GeyserBlockJavaPlayers] Disabling GeyserBlockJavaPlayers v1.2-SNAPSHOT`

I don't understand 😶

**Comment by Konicai** [comment]
Try redownloading the plugin.

**Comment by Senpapuh** [comment]
I already did it but it doesn't work
![Screenshot_20230703_123717_Chrome](https://github.com/kejonaMC/GeyserBlockJavaPlayers/assets/76405354/143bead8-f788-4ace-b82c-702fb106e64a)

**Comment by Senpapuh** [comment]
> Try redownloading the plugin.

With version 1.19.4 I don't have errors but with the new version I do 😶

**Comment by Konicai** [comment]
Ah whoops, I thought this was GeyserBlockPlatform. I'll fix this later tonight or tomorrow.

**Comment by Senpapuh** [comment]
It would be very helpful
Thanks

**Comment by Konicai** [comment]
Fixed
